March 2019 updates

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -1,8 +1,16 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set +x
 
 BASE_DIR=`cd "$(dirname "$0")"; pwd`
-source "$BASE_DIR/config"
+
+CONFIG=$BASE_DIR/config
+source "$CONFIG" 2> /dev/null || {
+  CONFIG=$CONFIG.sample
+  source "$CONFIG" 2> /dev/null || {
+    echo "File \"$CONFIG\" was not found!"
+    exit 1
+  }
+}
 
 mkdir -p "$MIRROR_DIR" && cd $_
 
